version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      # Il volume persisterà i modelli scaricati
      - ollama_data:/root/.ollama
  # Container ausiliario "usa-e-getta" per scaricare automaticamente il modello LLM ai primi avvii
  ollama-pull-model:
    image: ollama/ollama:latest
    restart: "no"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: /bin/sh
    command: -c "sleep 10 && ollama pull qwen2.5-coder && echo 'Modello qwen scaricato con successo!'"

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    command: ["uvicorn", "app.api2:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      ollama:
        condition: service_started
    volumes:
      - ./data/uploaded_dbs:/app/data/uploaded_dbs


volumes:
  ollama_data:
